name: Executar Script Python

on:
  push:
    branches:
      - main  # Altere para o nome da sua branch principal, se necessário
      - master

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Substitua '3.x' pela versão do Python que você deseja usar

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Se você tiver um arquivo requirements.txt

    - name: Executar script Python
      run: |
        python script.py
